---
- name: sample playbook testing API call to AUT-SIT-APIC1
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Query Specific access_port_selector under given leaf_interface_profile
    cisco.aci.aci_access_port_to_interface_policy_leaf_profile:
      hostname: 44.171.64.45
      username: admin
      password: C!scoLab20
      use_proxy: no
      validate_certs: no
      interface_profile: "1001_LINP"
      access_port_selector: "1.1_LINS"
      state: query
    delegate_to: localhost
    register: query_result

  - name: extracting IPG_NAME & DESCRIPTION associated to access port selector
    set_fact:
      IPG_NAME: query_result.current[0].infraHPortS.children[1].infraRsAccBaseGrp.attributes.tDn.split('-')[1]
      # DESCRIPTION: "{{query_result.current[0].infraHPortS.children[0].infraPortBlk.attributes.descr}}"

  - name: printing IPG NAME
    debug:
      var: query_result
