---
- name: sample playbook testing API call to AUT-SIT-APIC1
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Query Specific access_port_selector under given leaf_interface_profile
    cisco.aci.aci_bd:
      host: 10.254.163.201
      username: admin
      password: C!scoLab20
      validate_certs: no
      use_proxy: no
      state: query
    delegate_to: localhost
    register: query_result

  - name: extracting IPG_NAME & DESCRIPTION associated to access port selector
    set_fact:
      BD_NAME: "{{ query_result.current[:] }}"
 
  - name: degud BD list
    debug:
      var: BD_NAME
